# Generated by Django 5.0.1 on 2024-02-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_data_award_alter_data_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_description', models.CharField(max_length=500, verbose_name='Главное Описание')),
                ('title1', models.CharField(max_length=255, verbose_name='Название 1')),
                ('description1', models.CharField(max_length=255, verbose_name='Описание1')),
                ('title2', models.CharField(max_length=255, verbose_name='Название 2')),
                ('description2', models.CharField(max_length=255, verbose_name='Описание 2')),
                ('image', models.ImageField(upload_to='portfolio_image/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255, verbose_name='Количество')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='image_service/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
    ]
